name: Automated postman tests

on: 
    schedule:
      - cron: "36 14 * * 1-5"

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/tests
    name: automated-api-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create directory for reports 
        run: mkdir -p Reports 

      - name: Install node
        uses: actions/checkout@v3
        with:
          node-version: '16.x'

      - name: Install Newmann
        run: 
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run collection
        run: 
          newman run ms_parametrage.postman_collection.json -e environment.postman_environment.json --reporter-html-export > report.html 

      - name: Send reports to folder
        uses: actions/upload-artifact@v2
        with: 
          name: report.html
          path: Reports

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "API testing report"
          body: "Find attached to this mail the report of execting the tests of dgi microservices"
          recipients: 'hawawou.oumarou@abyster.com'
          attachment: 'Reports/report.html'
          from: Me
        
      
