name: Automated postman tests

on: 
    schedule:
      - cron: "05 12 * * 1-5"

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/tests
    name: automated-api-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create directory for reports 
        run: mkdir Reports 

      - name: Install node
        uses: actions/checkout@v3
        with:
          node-version: '16.x'

      - name: Install Newmann
        run: 
          echo "Installing Newmann"
          npm install newman -g
          npm install newman reporter

      - name: Run collection
        run: 
          newman run ms_parametrage.postman_collection.json -e environment.postman_collection.json --reporters cli,json --reporter-json-export outputfile.json

      - name: Send reports to folder
        uses: actions/upload-artifact@v2
        with: 
          name: Report
          path: Reports

      # - name: Send email with report
      #   uses: dawidd6/action-send-mail@v3
        
      
